### PR TITLE
[TECHNICAL-SUPPORT] LPS-71741 Chat portlet inconsistent behaviour when changing page and close/reopen

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @natecavanaugh 

Following your suggestions, I added an new UUID field to the Chat Entry model and extended the service API call with it.
On the frontend (**main.js**), when the entries are polled from the backend, `entryUuid` is used to check if an outgoing message was echoed on the chat window. In that is the case, the message is skipped when updating the window with the messages list.

After extending the API, I had some problems with compiling **chat-api** and **chat-service** though.

**chat-service** failed because it could not recognize the new field and methods in the API, I think because **chat-api** could not compiled in the first place.
chat-api in turn fails with this error during the source code processing via findBugsMain:

```
The following errors occurred during analysis:
  Cannot open codebase filesystem:C:\repok\liferay-portal\modules\apps\chat\chat-api\classes\com\liferay\chat\constants\packageinfo
    java.io.IOException: Wrong magic bytes of 76657273 for zip file C:\repok\liferay-portal\modules\apps\chat\chat-api\classes\com\liferay\chat\constants\packageinfo of 13 bytes
      At edu.umd.cs.findbugs.classfile.impl.ZipFileCodeBase.<init>(ZipFileCodeBase.java:87)
```

findBugsMain fails also if the API is not changed.

Have you ever met with this kind of compilation error in the Chat module?

Also, could you please check if the overall solution is OK?

Thank you very much!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Hey @dustinryerson I also wanted to ask you if you have met with those errors, or maybe have an idea what could be done to them?

Apparently it effects also the test results (see above), since the failure to build chat-api prevents chat-service to recognize the API changes.

Thank you,
István

**Comment by natecavanaugh** [comment]
@IstvanD I spoke with @Ithildir yesterday about the errors. He was able to reproduce it on master, and is going to take a look at it as soon as he can.

I believe it *might* have something to do with Gradle 3.3 and findBugs dumping out it's errors to stderr (based on [this ticket](https://github.com/gradle/gradle/issues/1094), specifically, [this comment](https://github.com/gradle/gradle/issues/1094#issuecomment-271959752)).

I'm going to review this one, but I'll wait till I can deploy it to push it up to Brian. If you guys are able to figure it out though, let me know  :)

**Comment by Ithildir** [comment]
Hi @natecavanaugh and @IstvanD,
I sent a fix for the `findbugsMain` problem at https://github.com/brianchandotcom/liferay-portal/pull/48197.

**Comment by natecavanaugh** [comment]
Thanks @Ithildir!

**Comment by IstvanD** [comment]
thank you!

**Comment by IstvanD** [comment]
Thanks to the changes in LPS-71795, the packageinfos errors are no longer appearing, however, I still have findBugs related problems when building chat-api,

At the end of the build process, I receive this error:

```
Done with analysis
:apps:chat:chat-api:findbugsMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:chat:chat-api:findbugsMain'.
> FindBugs rule violations were found. See the report at: file:///C:/repok/liferay-portal/modules/apps/chat/chat-api/build/reports/findbugs/main.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I checked the report (main.html), but I found only warning messages regarding bad coding practices.

```
Bad practice Warnings 

CN  com.liferay.chat.model.EntryWrapper.clone() does not call super.clone() 
CN  com.liferay.chat.model.StatusWrapper.clone() does not call super.clone() 
Se  com.liferay.chat.util.comparator.BuddyComparator implements Comparator but not Serializable 

```

I'm not sure if these warnings should be enough for the building process to fail. The code changes in chat-api are auto generated.

Maybe a full portal rebuild will yield different results, I'll try that next, and come back with them.

Bests,
István

**Comment by IstvanD** [comment]
@natecavanaugh : by the way, should we stick with the method of adding an additional ID field to the Chat entry model? 
Since we want to eventually provide the solution to the customer as a fix for version 6.2, where interface changes are not allowed, only for special cases.

**Comment by natecavanaugh** [comment]
@IstvanD I'm actually getting errors building, but it's not related to findbugs:
```
/Users/ncavanaugh/Dev/Liferay/Master/liferay-portal/modules/apps/chat/chat-service/src/main/java/com/liferay/chat/internal/poller/ChatPollerProcessor.java:85: error: no suitable method found for addEntry(long,long,long,String,String)
                        EntryLocalServiceUtil.addEntry(
                                             ^
    method EntryLocalServiceUtil.addEntry(Entry) is not applicable
      (actual and formal argument lists differ in length)
    method EntryLocalServiceUtil.addEntry(long,long,long,String) is not applicable
      (actual and formal argument lists differ in length)
    method EntryLocalServiceUtil.addEntry(long,long,String) is not applicable
      (actual and formal argument lists differ in length)
/Users/ncavanaugh/Dev/Liferay/Master/liferay-portal/modules/apps/chat/chat-service/src/main/java/com/liferay/chat/internal/poller/ChatPollerProcessor.java:241: error: cannot find symbol
                        entryJSONObject.put("entryUuid", entry.getEntryUuid());
                                                              ^
  symbol:   method getEntryUuid()
  location: variable entry of type Entry
/Users/ncavanaugh/Dev/Liferay/Master/liferay-portal/modules/apps/chat/chat-service/src/main/java/com/liferay/chat/model/impl/EntryModelImpl.java:338: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/ncavanaugh/Dev/Liferay/Master/liferay-portal/modules/apps/chat/chat-service/src/main/java/com/liferay/chat/model/impl/EntryModelImpl.java:348: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/ncavanaugh/Dev/Liferay/Master/liferay-portal/modules/apps/chat/chat-service/src/main/java/com/liferay/chat/service/impl/EntryLocalServiceImpl.java:42: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/ncavanaugh/Dev/Liferay/Master/liferay-portal/modules/apps/chat/chat-service/src/main/java/com/liferay/chat/service/impl/EntryLocalServiceImpl.java:85: error: cannot find symbol
                entry.setEntryUuid(entryUuid);
                     ^
  symbol:   method setEntryUuid(String)
  location: variable entry of type Entry
/Users/ncavanaugh/Dev/Liferay/Master/liferay-portal/modules/apps/chat/chat-service/src/main/java/com/liferay/chat/service/persistence/impl/EntryPersistenceImpl.java:4862: error: cannot find symbol
                entryImpl.setEntryUuid(entry.getEntryUuid());
                                            ^
  symbol:   method getEntryUuid()
  location: variable entry of type Entry
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors
:apps:chat:chat-service:compileJava FAILED
```

So for me, it appears to be an issue with the API change, but no word about findbugs for me.

Do you know what could be causing this?

As for your other question, I think it might be the only way to do it accurately and with minimal issues for the customer. The other proposed change of serializing a JSON object and sending that as the message has a higher risk of breaking and a lot more incompatibility long term.

I don't think adding a new field should cause any errors, though, at least that I can think of.

**Comment by IstvanD** [comment]
Hey @natecavanaugh 

I'm almost sure that the errors in chat-service are there because chat-api couldn't compile in the first place. 
For example, there is the parameter mismatch error for EntryLocalServiceUtil.addEntry(). This is because ChatPollerProcessor still sees only the 4-paramter EntryLocalServiceUtil.addEntry(long,long,long,String), not the one with 5 parameters added in chat-api.
Similarly, getEntryUuid and setEntryUuid only exist in the updated chat-api.

**Comment by IstvanD** [comment]
Hey @Ithildir 

Have you managed to find something about the other error of findBugs which is still remaining, and blocking the compilation of chat-api? https://github.com/natecavanaugh/liferay-portal/pull/4113#issuecomment-292874833

Thanks in advance!

Br,
István

**Comment by Ithildir** [comment]
Hi @IstvanD,
What compilation error are you having? `ant all` on CI is not failing, and running `gradlew jar` from `chat-api` completes successfully, here on my machine.

**Comment by Ithildir** [comment]
And, as for the FindBugs problems, it appears that other `*-api` modules have the same issues, for example `bookmarks-api`.

**Comment by IstvanD** [comment]
Hey @Ithildir 

I get the error message that the build fails with an exception, but without any details about what was the exact cause. 

```
Done with analysis
:apps:chat:chat-api:findbugsMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:chat:chat-api:findbugsMain'.
> FindBugs rule violations were found. See the report at: file:///C:/repok/liferay-portal/modules/apps/chat/chat-api/build/reports/findbugs/main.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
I checked the report (main.html), but I found only warning messages regarding bad coding practices.
```
Bad practice Warnings 

CN  com.liferay.chat.model.EntryWrapper.clone() does not call super.clone() 
CN  com.liferay.chat.model.StatusWrapper.clone() does not call super.clone() 
Se  com.liferay.chat.util.comparator.BuddyComparator implements Comparator but not Serializable 

```
This is on the master branch.

**Comment by IstvanD** [comment]
Anyway, I'll close this pull since I discovered some logic errors in myx fix, when I tested it on 6.2.
Those were not related to the compilation errors.

@natecavanaugh : I'll resend the pull to ee-6.2.x if you want to test the solution.
